config/routes.rb
Rails.application.routes.draw do
devise_for :users
root to:"homes#top"
get 'show/edit'
get'home/about' => 'homes#top', as: 'about'
resources :books, only: [:create, :index, :show, :destroy, :edit]
get 'books/:id/edit' => 'books#edit'
resources :users, only: [:index, :show, :edit, :update]
patch 'books/:id' => 'books#update', as: 'update_book'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  validates :title, presence: true
  validates :body, length: { maximum: 200 }, presence: true

end

app/models/user.rb
class User < ApplicationRecord

  validates :name, uniqueness: true,
    length: { minimum: 2, maximum: 20 }
  validates :email, presence: true
  validates :introduction, length: { maximum: 50 }

  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_one_attached :profile_image

def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!, except: [:top]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

protected

  def configure_permitted_parameters
       devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
  end

  # def create
  #   @book = Book.new(book_params)
  #   if @book.user_id = current_user.id
  #     @book.save
  #     flash[:notice] = "You have created book successfully"
  #     redirect_to book_path(@book.id)
  #   else
  #     flash.now[:danger] = "You haven't created book successfully"
  #     render :index
  # end
  # end

 def create
  @book = Book.new(book_params)
  @book.user_id = current_user.id
  if @book.save
   flash[:notice] = "You have created book successfully."
   redirect_to book_path(@book)
  else
   flash.now[:danger] = "You haven't created book successfully"
   @books = Book.all
   render :index
  end
 end


  def index
    @books = Book.all
    @book = Book.new
  end

  def show
   @books = Book.find(params[:id])
   @book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  unless @book.user == current_user
    redirect_to books_path
end
  end

 def update
    @book = Book.find(params[:id])
  if @book.user != current_user
      redirect_to book_path
  end

  if @book.update(book_params)
       flash[:notice] = "You have updateed book successfully"
        redirect_to book_path
  else
       flash.now[:danger] = "You haven't updateed book successfully"
       render :edit
  end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.user != current_user
       redirect_to  book_path(@book)
    else
      @book.destroy
      flash[:success] = "You have destroyed book successfully"
      redirect_to  books_path
    end
  end

    def book_params
    params.require(:book).permit(:title, :body)
    end
    end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
     @user = User.find(params[:id])
     @books = @user.books
     @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  unless @user == current_user
    redirect_to user_path(current_user)
  end
  end

 def update
    @user = User.find(params[:id])
    if @user.id != current_user.id
       redirect_to user_path(@user)
    end

    if @user.update(user_params)
      flash[:notice] = "You have updateed user successfully"
      redirect_to user_path(@user)
    else
      flash.now[:danger] = "You haven't updateed book successfully"
      render :edit
  end
  end

  def index
    if @users = User.all
       @user = User.new
       @books = Book.all
       @book = Book.new
    else
      flash.now[:danger] = "Book wasn't successfully show."
      render '/user'
  end
end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<!--部分テンプレート-->
<div class="col-md-3 mt-4">
<h2>User info</h2>
<h3><%= image_tag user.get_profile_image(100,100) %></h3>
<table class="table">
<tr>
  <th>name</th>
  <th><%= user.name %></th>
</tr>
<tr>
  <th>introduction</th>
  <th><%= user.introduction %><th>
</tr>
</table>
<%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
<div class="sample"><i class="fas fa-user-cog"></i></div>
<% end %>

<h2 class="mt-3">New book</h2>
　　<%= form_with model: book do |f| %>
    Title<br>
      <%= f.text_field :title %><br>
    Opinion<br>
      <%= f.text_area :body %><br/>
      <input type="submit" value="Create Book" class="btn btn-success">
 <% end %>
</div>

app/views/books/edit.html.erb
<div class="container">
<div class="row mt-4">
<div class="mx-auto">
<h1>Editing Book</h1>

<% if @book.errors.any? %>
  <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
  <ul>
   <% @book.errors.full_messages.each do |message| %>
   <li><%= message %></li>
  </ul>
  <% end %>
<% end %>


<%= form_with model: @book, url: update_book_path(@book.id), method: :patch do |b| %>

  Title<p>
  <%= b.text_field :title %><p>

  Opinion<p>
  <%= b.text_area :body %>
<p>

  <%= b.submit 'Update Book' %>
<% end %>

<%= link_to "Show", book_path %>
|
<%= link_to "Back", books_path %>
</div>
</div>
</div>

app/views/books/index.html.erb
<%= flash[:notice] %>
<div class="container">

<% if @book.errors.any? %>
  <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
  <% end %>

<% end %>

<div class="row">

<%= render 'book', book: @book, user: current_user %>
<!--部分テンプレを呼び出しをしている-->

<div class="col-md-8 offset-md-1 mt-4">
<h2>Books</h2>
<table class="table">
  <thead>
    <tr>
    <th scope="col" colspan="1"></th>
      <th scope="col">Title</th>
      <th scope="col">Opinion</th>
    </tr>
  </thead>
  <tbody>
<% @books.each do |b| %>
    <tr>
    <td><%= link_to user_path(b.user.id) do %>
    <%= image_tag b.user.get_profile_image(100, 100) %>
    <% end %>
    </td>
    <td>
    <%= link_to book_path(b.id) do %>
    <%= b.title %>
    <% end %>
    </td>
    <td><%= b.body %></td>
    </tr>
    <% end %>
</tbody>
</table>
</div>
</div>
</div>

app/views/books/show.html.erb
<%= flash[:notice] %>
<div class="container">
<div class="row">

<%= render 'book', book: @book, user: @books.user %>

<div class="col-md-8 offset-md-1">
<h2>Book detail</h2>
<table class="table">
<tbody>
<tr>
      <td>
      <%= link_to user_path(@books.user.id) do %>
      <%= image_tag @books.user.get_profile_image(100,100) %><br>
      <%= @books.user.name %>
      <% end %>
      </td>

      <td>
      <%= link_to book_path(@books.id) do %>
      <%= @books.title %>
      <% end %>
      </td>


      <td>
      <%= @books.body %>
      </td>

      <% if @books.user.id == current_user.id %>
      <td>
      <%= link_to "Edit", edit_book_path(@books.id), class: "btn btn-success" %>
      </td>

      <td>
      <%= link_to "Destroy", book_path(@books.id), method: :delete, "data-confirm" => "本当に消しますか？", class: "btn btn-danger text-white" %>
      </td>
      <% end %>


</tr>
</tbody>
</table>
</div>
</div>
</div>

app/views/homes/about.html.erb
<div class="container">
<div class="row mt-4">
<div class="mx-auto">
<h1>Welcome to
<i class="fas fa-book"></i><strong>Bookers !</strong></h1>
</div></div>

</div>
<div class="container mt-4">
  <div class="row">
  <div class="mx-auto">
<p><p>CopyRight Infratop.inc
</div>
</div>
</div>

app/views/homes/top.html.erb
<%= flash[:notice] %>

<div class="container">
<div class="row mt-4">
<div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
<h1>welcome to
<i class="fas fa-book"></i><strong>Bookers !</strong></h1>
</div></div>

<div class="row">
<div class="mx-auto">
In<i class="fas fa-book"></i><strong>Bookers</strong>,<p><p>
you can share and exchange your opinions , inpressions , and emotions<p>
about various books!
<p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
        <%= link_to 'Log in',new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
        <%= link_to 'Sign up',new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container mt-4">
  <div class="row">
  <div class="mx-auto">
<p><p>CopyRight Infratop.inc
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/8cba356135.js" crossorigin="anonymous"></script>
    <title>Bookers2Ver2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light  bg-dark">
        <div class="container">
          <a class="navbar-brand p-2 text-white" href="/">Bookers</a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

<% if user_signed_in? %>

<li>
<%= link_to user_path(current_user.id), class: 'nav-link text-white' do %>
<i class="fas fa-home"></i>Home
<% end %>
</li>

<li>
<%= link_to users_path, class: 'nav-link text-white' do %>
<i class="fas fa-users"></i>Users
<% end %>
</li>

<li>
<%= link_to books_path, class: 'nav-link text-white' do %>
<i class="fas fa-book-open"></i>Books
<% end %>
</li>

<li>
<%= link_to destroy_user_session_path, class: 'nav-link text-white' do %>
<i class="fas fa-sign-out-alt"></i>Log out
<% end %>
</li>

<% else %>

<li>
<%= link_to root_path, class: 'nav-link text-white' do %>
<i class="fas fa-home"></i>Home
<% end %>
</li>

<li>
<%= link_to about_path, class: 'nav-link text-white' do %>
<i class="fas fa-link"></i>About
<% end %>
</li>

<li>
<%= link_to new_user_registration_path, class: 'nav-link text-white' do %>
<i class="fas fa-user-plus"></i>Sign up
<% end %>
</li>

<li>
<%= link_to new_user_session_path, class: 'nav-link text-white' do %>
<i class="fas fa-sign-in-alt"></i>Log in
<% end %>
</li>
<% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
    <%= yield %>
    </main>

  </body>

</html>

app/views/users/_user.html.erb
<!--部分テンプレート-->
<div class="col-md-3">
<h2>User info</h2>

<h3><%= image_tag user.get_profile_image(100, 100) %></h3>

<table class="table">
<tr>
  <th>name</th>
  <th><%= user.name %></th>
</tr>
<tr>
  <th>introduction</th>
  <th><%= user.introduction %><th>
</tr>
</table>

<%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
<div class="sample"><i class="fas fa-user-cog"></i></div>
<% end %>

<h2 class="mt-3">New book</h2>
<%= form_with model: book do |f| %>
    Title<br>
      <%= f.text_field :title %><br>
    Opinion<br>
      <%= f.text_area :body %><br/>
      <input type="submit" value="Create Book" class="btn btn-success">
 <% end %>
</div>

app/views/users/edit.html.erb
<div class="container">
<div class="row">
<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto mt-4">
<h2>User info</h2>


<% if @user.errors.any? %>
  <h3><%= @user.errors.count %> errors prohibited this obj from being saved:</h3>
  <ul>
   <% @user.errors.full_messages.each do |message| %>
   <li><%= message %></li>
  </ul>
  <% end %>
<% end %>


<%= form_with model: @user do |f| %>
  <label for="inputName">Name</label><br>
   <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"name"%>
  <%= @user.name %>"><br>-->

  <br><label for="inputImage">Image</label><br>
  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
  <br><br>

  <label for="inputIntroduction">Introduction</label><br>
  <textarea class="form-control introduction" name="user[introduction]" id="introduction" value="<%= @user.introduction %>"><%= @user.introduction %></textarea>

<input type="submit" value="Update User" class="btn btn-secondary">
<% end %>
</div></div></div>

<div class="container mt-4">
<div class="row">
<div class="mx-auto">
<p><p>CopyRight Infratop.inc
</div>
</div>
</div>

app/views/users/index.html.erb
<div class="container">
<div class="row">

<%= render 'user', book: @book, user: current_user %>

<div class="col-md-8 offset-md-1 mt-4">

<h2>Users</h2>
<table class="table">
  <thead>
    <tr>
      <th scope="col">image</th>
      <th scope="col">name</th>
      <th scope="col" colspan="1"></th>
    </tr>
  </thead>
  <tbody>
<% @users.each do |us| %>
    <tr>
    <td><%= image_tag us.get_profile_image(100,100) %></td>
    <td><%= us.name %></td>
    <td><%= link_to "Show", user_path(us.id) %></td>
    <% end %>
</tbody>
</table>
</div>
</div>
</div>

app/views/users/show.html.erb
<%= flash[:notice] %>

<div class="container px-5 px-sm-0">
<div class="row">

<%= render 'user', book: @book, user: @user %>

<div class="col-md-8 offset-md-1 mt-3">
<h2>Books</h2>
<table class="table">
<thead>
<tr>
     <td colspan="1"></td>
     <td>Title</td>
     <td>Opinion</td>
</tr>
</thead>

<tbody>
<% @books.each do |book| %>
<tr>
      <td>
      <%= link_to user_path(book.user.id) do %>
      <%= image_tag book.user.get_profile_image(100, 100) %>
      <% end %>
      </td>

      <td>
      <%= link_to book_path(book.id) do %>
      <%= book.title %>
      <% end %>
      </td>

      <td>
      <%= book.body %>
      </td>
</tr>
<% end %>

</tbody>
</table>
</div>
</div>
</div>